disabled_rules: # rule identifiers to exclude from running

included: # paths to include during linting. `--path` is ignored if present.
    - Sources/
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Packages/
force_cast: warning 
line_length: 180
file_length:
    warning: 800
    error: 1200
large_tuple:
    warning: 4
    error: 8
function_body_length:
    warning: 800
    error: 1000
type_body_length:
    warning: 800
    error: 1000
cyclomatic_complexity: 20
variable_name:
  excluded: # excluded via string array
    - UUI
    - fm
    - df
    - id
